print("Hello, World!")
print("This is a test script.")    
print("It demonstrates basic print functionality in Python.")
print("You can print multiple lines of text using the print() function.")
print("Feel free to modify this script and add your own code!")
print("Goodbye!")